### ISSUE TITLE
Canon Printer return to supplier

### ISSUE THREAD

**Issue by Apbasanez** [CitySportsClub/IT-Admin#7]
Dave please call Need Ink & tell them that we have 2 printers that's unused and for pull-out and 1 printer needs cleaning.

**Comment by Apbasanez** [comment]
Followup tomorrow. 12/15 scheduled for cleaning only. Scheduled na for pullout.

**Comment by Apbasanez** [comment]
Tech already cleaned 1 Canon LBP2900 printer. 2 printer for pullout to be scheduled.

**Comment by dmsolon** [comment]
Already called Need Ink. Scheduled na tomorrow for pullout. Followup nalang tom.

**Comment by dmsolon** [comment]
Pulled out na ang mga printers sir 👍
